### ISSUE TITLE
Add a way to access the 18F Guides home page from each guide

### ISSUE THREAD

**Issue by jenniferthibault** [18F/guides-template#17]
People who are reading one guide might not know that we have other handy documents on different topics. It would be nice to have a away back to the main guide list page (https://pages.18f.gov/guides/) from any interior page of any guide, but certainly from the landing page for each guide (https://pages.18f.gov/agile/ https://pages.18f.gov/content-guide/ etc).

Perhaps it could go either in the footer, or up top under the blue header line?

The style should probably be the same as for the team page:

![screen shot 2015-07-09 at 10 52 45 am](https://cloud.githubusercontent.com/assets/11636908/8599018/0aaaec20-262c-11e5-956e-0a6dad8b4624.png)

**Comment by maya** [comment]
+1 

Another Idea is to have a parent link "18F Guides"
