### ISSUE TITLE
There is a maximum number of child stories that can be under a parent story and no way to scroll through more of them.

### ISSUE THREAD

**Issue by melodykramer** [18F/guides-template#26]
It appears that you can only place 12 child stories under a parent story. There is currently no way to scroll down to see more of them. (There are 15 child stories under the parent in this example.)

![screen shot 2015-07-31 at 1 11 30 pm](https://cloud.githubusercontent.com/assets/5784474/9013355/531c0d7c-3789-11e5-8fb6-dd74e11e0965.png)

**Comment by mbland** [comment]
@noahmanger Any ideas for an easy fix?

**Comment by mbland** [comment]
@melodykramer What repo is that Federalist guide from? I don't see it posted to https://pages.18f.gov.

**Comment by mbland** [comment]
Oh, duh... https://github.com/18F/federalist-content-guide

**Comment by melodykramer** [comment]
I'm still working on it :)

**Comment by mbland** [comment]
Although, @melodykramer, I have to ask: Is the bulk of https://pages.18f.gov/content-guide/ replicated in this guide? Any reason not to just refer people to the other Content Guide?

**Comment by melodykramer** [comment]
Yup, it's being built out for a client who wants a content guide all in one spot, I believe - makes it easy for them. I forked Content and checked with the WG first.

**Comment by mbland** [comment]
Ooookaaayyy... :confused: So much for the [DRY Principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by melodykramer** [comment]
Mike, the more I think about what you said, the more I think you're right on the mark - changing the sidebar to point to the Content guide, so if there are updates, they're reflected here. Thanks for the feedback.

**Comment by mbland** [comment]
Just tidying up here... This is also related to #63, which I hope to address shortly.
