### ISSUE TITLE
Vertical height triggers switch to mobile view

### ISSUE THREAD

**Issue by maya** [18F/guides-template#30]
Whenever I make my browser window shorter, it switches to mobile view, which I don't want. Most of the times this is an issue when I open up web inspector on the page.

Can we remove this vertical media query?

This is what it looks like:
<img width="573" alt="screen shot 2015-08-10 at 11 31 38 am" src="https://cloud.githubusercontent.com/assets/5249443/9179739/672685dc-3f53-11e5-9270-e58e935a54ff.png">

**Comment by carodew** [comment]
I found the same bug and wandered (on a meandering path) over here to log it. I usually have different app panes at half width or half height to see more than one thing at a time, so it was triggering the full width side nav layout on desktop. I was confused.

**Comment by maya** [comment]
Fixed via `guides-style` in: https://github.com/18F/guides-style/pull/25
