### ISSUE TITLE
give guidance about how to include custom scripts/stylesheets

### ISSUE THREAD

**Issue by afeld** [18F/guides-template#69]
For the [Before You Ship](https://pages.18f.gov/before-you-ship/) site, which uses this gem, I was trying to figure out a good way to include a script on every page of the site. Since the layout is embedded in the gem, I wasn't able to modify it directly. I ended up figuring out a workaround using a nested layout (see `_config.yml` and `_layouts/default.html` in https://github.com/18F/before-you-ship/pull/71), but it feels like a bit of a hack. Curious if there are other ideas about how to accomplish this?

/cc @fureigh

**Comment by mbland** [comment]
Yeah: https://github.com/18F/guides-style/#additional-scripts-and-styles

**Comment by afeld** [comment]
D'oh, thanks!
