### ISSUE TITLE
figure out how to share templates

### ISSUE THREAD

**Issue by afeld** [18F/guides-template#9]
As this is currently structured, the template being updated won't be reflected in the individual guides.

**Comment by mbland** [comment]
We could try bundling styles into a gem, using a mechanism similar to [how `jekyll_pages_api_search` provides an interface for injecting interface components](https://github.com/18F/jekyll_pages_api_search#usage).

Alternatively, if [the Hub's Hugo migration](https://github.com/18F/hub/issues/326) goes well, we may consider migrating the Guides as well. If so, [Hugo themes](https://gohugo.io/themes/overview/) would likely solve the problem.

**Comment by mbland** [comment]
Wow, holy way to never triage old issues, Batman! This is somewhat addressed by the [`guides_style_18f` gem](https://rubygems.org/gems/guides_style_18f) from [18F/guides-style](https://github.com/18F/guides-style/).
